version: '3.8'

services:
  database:
    image: postgres:13
    container_name: db-container
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  backend:
    build: ./src/backend
    container_name: backend-container
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/myapp
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build: ./src/events_frontend
    container_name: frontend-container
    ports:
      - "5174:5174"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge